apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  labels:
    app: dns-lookup
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dns-lookup
  template:
    metadata:
      labels:
        app: dns-lookup
        cluster: dns-lookup
    spec:
      containers:
        - name: backend
          image: ghcr.io/cynicdog/cloudnative-node.js-templates/plugins_clustered:latest
          imagePullPolicy: Always
          env:
            - name: HTTP_PORT
              value: "8080"
            - name: PORT_FORWARDED_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: CURRENT_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SERVICE_NAME
              value: "node-app.default.svc.cluster.local"
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            failureThreshold: 1
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          startupProbe:
            httpGet:
              path: /readiness
              port: 8080
            failureThreshold: 30
            periodSeconds: 10