apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: node-app
spec:
  selector:
    cluster: dns-lookup
  ports:
    - name: http
      port: 8080
      protocol: TCP
  publishNotReadyAddresses: true
  clusterIP: None