version: '3.8'

services:
  backend:
    image: ghcr.io/cynicdog/cloudnative-node.js-templates/auth_fastify:latest
    container_name: fastify-backend
    environment:
      REDIS_HOST: redis
      FRONTEND_HOST: vite-react-client
      FRONTEND_PORT: 4173
    ports:
      - "3000:3000"
    depends_on:
      - redis
    networks:
      - app-network

  frontend:
    image: ghcr.io/cynicdog/cloudnative-node.js-templates/auth_client:latest
    container_name: vite-react-client
    environment:
      PORT: 4173
      VITE_SERVER_URI: http://fastify-backend:3000
    ports:
      - "4173:4173"
    depends_on:
      - backend
    networks:
      - app-network
    command: ["npm", "run", "preview"]

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge