apiVersion: v1
kind: Service
metadata:
  name: node-app
spec:
  selector:
    cluster: dns-lookup
  ports:
    - name: http
      port: 8080
      protocol: TCP
  publishNotReadyAddresses: true
  clusterIP: None