name: Docker Build and Test

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    env:
      APP_NAME: node-cluster-app
      PROJECT_DIR: 1_nodes_in_cluster

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build Docker image
        run: |
          cd ${{ env.PROJECT_DIR }} && \
          docker build -t ghcr.io/${{ github.repository }}:latest .  

      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository }}:latest
