name: Docker Build and Push to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    env:
      APP_NAME: node-cluster-app
      PROJECT_DIR: 1_nodes_in_cluster

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Set lower case credentials
        run: |
          echo "REPO=${{ github.repository | toLowerCase() }}" >> "${GITHUB_ENV}"
          echo "ACTOR=${{ github.actor | toLowerCase() }}" >> "${GITHUB_ENV}"
          echo "GHCR_PAT=${{ secrets.GHCR_PAT }}" >> "${GITHUB_ENV}"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ env.ACTOR }}
          password: ${{ env.GHCR_PAT }}

      - name: Build Docker image
        run: |
          cd ${{ env.PROJECT_DIR }} && \
          docker build -t ghcr.io/${{ env.REPO }}:latest . 

      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/${{ env.REPO }}:latest